Title: Assignment 2: Rule-based analysis of Somali
Author: Brian W. Smith
Date: 8/20/2019
CSS: bws.css

<!-- Standard header. Change title in metadata -->

[USC Advanced Undergraduate Phonology](401_guide.html) ✳︎ Fall 2019 ✳︎ Smith
***

<div class="title">

[%title]

</div>

<!-- {{TOC}}-->

<!-- Content starts below -->

# Goals
- to develop, present, and argue for an SPE-style system of rules for a complicated data set

# Instructions
- Account for all phonological alternations in these data.
- Start with the data in part (A), and then, for each successive part (B–D), modify your analysis as needed by adding new rules or modifying existing ones
- Remember that the final set of rules you end up with must account for all of the data.
- Your analysis should conform to the assumptions we've been making:
	- Every morpheme has a unique UR.
	- Phonological rules manipulate features.
	- Rules apply in sequence.
	- Assume the Hayes (2009) feature set in the Dropbox folder.
- Otherwise, you are free to be as creative as you'd like:
	+ Abbreviatory conventions are allowed, if they provide a better analysis.
	- You can use abstract URs, if they provide a better analysis.
	- (I don't think you need either)
- Other things to note about the data:
	- You may assume a phonetically arbitrary /lt/ ➔ [ʃ] rule.
	- Vː indicates a long vowel, which has the feature [+long] in this feature system.

- Your write up must contain the following things:
	- **Description of alternations:** Clearly describe each alternation that you observe, in neutral terms.
	- **URs**: Clearly state the URs of each morpheme (each root and each suffix).
	- **Rules**: For each alternation, clearly state (and name) a phonological rule or rules which operate on the URs ing representations you posited.
	- **Discussion of alternatives**: If you could have handled a given alternation (e.g. X ~ Y) by assuming underlying X and rule X →  Y, discuss why that choice is better than the alternative (e.g. assuming underlying Y and rule Y →  X).
	- **Rule ordering and derivation**: In this problem, the order of rules matter. Provide an ordering argument, using proof-by-demonstration: for relevant sample inputs, ordering rule A before rule B achieves the correct result, while ordering B before A does not. (You may have to figure out the order of rules through trial and error)

- I've posted a handout including write-up tips. This handout is relevant for every assignment, and you should read it.

# How to write it up
- Write up your solution in the form of a short paper, with an introduction, titled sections, and a conclusion.
- You are encouraged to collaborate on solving the problem, but you must write up your own analysis.
- Possible sections:
	- Introduction - a sentence of two explaining what the write-up is about
	- Alternations - describe each of the alternations, using examples from the data to illustrate them. Make it clear what you think the morphemes are.
	- Rules and URs - for each alternation, provide a rule or rules. Make sure you define the rule formally and also in prose. This is a good place to justify why you formalized the rule the way you did, and provide support for your choices of underlying vs. derived sounds.
	- Rule ordering and derivation - provide a derivation for a set of inputs, showing that your analysis works. Choose inputs that undergo each rule. This is a good place to discuss rule ordering, and provide derivations showing that the rules must be in a certain order.
	- Conclusion - summarize what your analysis did.
	- Optional section: predictions - discuss testable predictions of your analysis.

# Data part A

| Singular		|Singular definite| Plural		| Gloss			|
| 		---		|		---		|		---		|		---		|
|	daːr		|	daːrta		|	daːro		|	house		|
|	geːs		|	geːsta		|	geːso		|	side		|
|	lug			|	lugta		|	luγo		|	leg			|
|	naːg		|	naːgta		|	naːγo		|	woman		|
|	tib			|	tibta		|	tiβo		|	pestle		|
|	sab			|	sabta		|	saβo		|	outcast		|
|	bad			|	bada		|	baðo		|	sea			|
|	ʕid			|	ʕida		|	ʕiðo		|	person		|
|	feːɖa		|	feːɖa		|	feːʐo		|	rib			|
|	ul			|	uʃa			|	ulo			|	stick		|
|	bil			|	biʃa		|	bilo		|	month		|
|	meːl		|	meːʃa		|	meːlo		|	place		|
|	kaliːl		|	kaliːʃa		|	kaliːlo		|	summer		|
			

# Data part B

| Singular		|Singular definite| Plural		| Gloss			|
| 		---		|		---		|		---		|		---		|
|	sun			|	sunta		|	sumo		|	poison		|
|	laːn		|	laːnta		|	laːmo		|	branch		|
|	sin			|	sinta		|	simo		|	hip			|
|	dan			|	danta		|	dano		|	affair		|
|	daːn		|	daːnta		|	daːno		|	river bank	|
|	saːn		|	saːnta		|	saːno		|	hide		|
			

# Data part C

| Singular		|Singular definite| Plural		| Gloss			|
| 		---		|		---		|		---		|		---		|
|	nirig		|	nirigta		|	nirgo		|	baby female camel|
|	gaβaɖ		|	gaβaɖa		|	gabɖo		|	girl		|
|	gaʕan		|	gaʕanta		|	gaʕmo		|	arm			|
|	hoɣol		|	hoɣoʃa		|	hoglo		|	downpour	|
|	baɣal		|	baɣaʃa		|	baglo		|	mule		|
|	waħar		|	waħarta		|	waħaro		|	female kd	|
|	kefed		|	kefeda		|	kefeðo		|	pan			|	
|	ʕilin		|	ʕilinta		|	ʕilino		|	female dwarf|
|	bohol		|	bohoʃa		|	boholo		|	hole		|
					
# Data part D	

|3sg. masc. past| 3sg. fem. past| 1 pl. past	| Gloss 		|
| 		---		|		---		|		---		|		---		|
|	suɣaj		|	sugtaj		|	sugnaj		|	wait		|
|	kaβaj		|	kabtaj		|	kabnaj		|	fix			|
|	siðaj		|	sidaj		|	sidnaj		|	carry		|
|	dilaj		|	diʃaj		|	dillaj		|	kill		|
|	ganaj		|	gantaj		|	gannaj		|	aim			|
|	tumaj		|	tuntaj		|	tunnaj		|	hammer		|
|	argaj		|	aragtaj		|	aragnaj		|	see			|
|	gudbaj		|	guðubtaj	|	guðubnaj	|	cross a river|
|	qoslaj		|	qosoʃaj		|	qosollaj	|	laugh		|
|	hadlaj		|	haðaʃaj		|	haðallaj	|	talk		|



