Title: Syllables and typology in OT
Author: Brian W. Smith
Date: 10/9/2019
CSS: bws.css

<!-- Standard header. Change title in metadata -->

[USC Advanced Undergraduate Phonology](401_guide.html) ✳︎ Fall 2019 ✳︎ Smith
***

<div class="title">

[%title]

</div>

{{TOC}}

***

# The syllable

![The syllable](syllable.svg)

- Syllable boundaries are marked with "." in the IPA.
-   Every syllable in every language has a nucleus - usually a vowel, but sometimes a consonant.
    +   The feature [+syllabic] is commonly used for sounds that can be the nucleus of a syllable (usually but not always vowels).
-   Classic syllabification rules, which are pretty universal:
    - Step 1. Build nuclei of syllables.
    - Step 2. Add consonants as onsets (as many as legal).
        + Maximal Onset Principle: VCV is always syllabified as V.CV
    - Step 3. Join unsyllabified consonants as codas.
-  Languages differ in the inventory of permitted syllable types, including answers to questions like:
    - What are possible nuclei?
    - Are onsets required?
    - Are codas permitted?
    - Are complex onsets permitted? Complex codas? Both?
    - What are legal onsets?
    - What are legal codas?
    - How are medial consonant clusters syllabified?
        - E.g., VCCV syllabified as VC.CV or V.CCV?
    - Does a coda make a syllable heavy?

# Cross-linguistic tendencies regarding what can be an onset, coda, and nucleus
- Codas tend to have fewer contrasts than onsets (Itô 1986, Goldsmith 1990)
- Sonority sequencing principle (Selkirk 1984)
    - Syllables tend to have highest sonority in the nucleus, and lowest sonority at the margins.

| --- | --- |
| Vowels | low vowels |
|   | mid vowels |
|   | high vowels|

|Glides  | glides    |

|Liquids  | rhotics   |
|   | laterals  |

| Nasals | nasals    |

| Obstruents | voiced fricatives |
|   | voiced stops |
|   | voiceless fricatives |
|   | voiceless stops |
[The sonority scale]

- The syllable contact law (Murray & Vennemann 1983)
    - There is a cross-linguistic preference for syllable contacts with falling sonority.
- Onsets independently tend to be less sonorous (e.g. Gnanadesikan 1995)
    + Example: acquisition of English (Gnanadesikan 1995)
        + blue = [bu], sky = [gaɪ], snow = [noʊ], balloon = [bun]
    - Example: Sardinian has a ban on rhotic and glide onsets, but allows rhotic and glide codas. (Smith 2003)
- More sonorous codas are more likely to be counted as heavy (see Zec 2007)
    + Example: In Gonja and Kwak'hala syllables with coda nasals and liquids are heavy, but syllables with coda obstruents are light.


# Contrastive syllabification?
- Syllabification is never contrastive.
    - No language has a minimal pair in which the words differ only in syllabification.
    - E.g., [a.ma] 'orange' vs. [am.a] 'lemon'.
    - Instead, syllabification is completely predictable within a language.
    -  When it *looks* contrastive, there's always an explanation in terms of other differences in underlying forms (e.g., morpheme boundaries in *night rate* vs. *nitrate*).
-   Consequence: in OT, there are no faithfulness constraints that refer to the syllabification of the input, and syllabification is usually taken not to be in the input at all.

# Why do phonologists think syllable structure exists?
- What is the phonetic reality of syllables? Psychological reality?
    - No perfect phonetic correlates.
    - Syllable counting is unreliable.
    - Speakers' application of syllable-based rules sometimes clashes with syllabification judgments (see work by Marie-Hélène Côté for examples).
- In fact, some phonologists (Steriade, Côté, most prominently) have proposed doing away with syllables entirely. 
    - The thinking: if you can model all of the data that seem to require syllables without using syllable structure, the syllable-less model is better due to parsimony. (Recall: "Do not posit complexity without necessity.")
    - In SPE, there were no syllables at all!
- Here's one theory-internal argument for syllables: we see rule after rule that looks like this:
    - C →   … / __ {C, #}   
    - The use of braces makes us think we've missed something - the two cases must have something in common, especially when they keep occurring together.
    - How might we translate this rule into syllable terms?
        + This requires invoking cross linguistic tendencies in syllabification.
-  Syllables also make it easier to describe stress patterns.
    - "Stress the penultimate syllable if it has a coda. Otherwise, stress the antepenultimate syllable"
    - CV.VC.CCVC → CV.VC.CCVC
    - CV.VC.CVC → CV.VC.CVC
    - CV.V.CVC → CV.V.CVC
    - CV.V.VC → CV.V.VC
    - How could we write the rule without syllables?
        + Note: Donca Steriade has worked out a syllable-less OT analysis of stress patterns like this in a series of papers (Steriade 2009 et seq.), so it *is* possible.
- Syllables also make it easier to state patterns of reduplication and truncation, e.g. "The output of truncatation is heavy syllable", "Copy the first two syllables."

# Typology of onsets and codas 

- Data below are from Blevins 1995, and the typology is originally described in Jakobson 1962.
    + I'm excluding complex codas and onsets for now.

|  Language |  Onsets  | Codas  | Possible syllables |
| --- | --- | --- | ---|
| Arabela, Siona, Piro, Hua,  |required    |forbidden  | CV|
| Totonac, Klamath, Nisqually, Tunica, Sedang, Dakota, Thargari |  required |    optional   | CV      CVC|
| Pirahã, Mazateco Fijian, Cayuvava   |optional    |forbidden |  CV  V|
| English, Gilyak Finnish, Tamazight Berber, Cairene Arabic, Spanish, Italian, Mokilese, Cuna |  optional |   optional |   CV  V   CVC     VC |

-   What hypothetical language types are missing from this typology? (Don't look below yet!)
-   Typology of syllable structure
    -  There are languages lacking syllables with initial vowels and/or syllables with final consonants, but there are no languages devoid of syllables with initial consonants or of syllables with final vowels. (Jakobson 1962: 526)
    - If a language has syllables without onsets, it also has syllables with onsets.
    - If a language has syllables with codas, it also has syllables without codas.
    - Every language has at least some CV syllables.
    - If-then statements like the two above are called **implicational universals**.

# Acquisition of codas and onsets
-   In acquisition, children (mostly) mirror this typology, using onsets before they use codas. 

|Stage     |  1  |  2 |  3 | 4   |5    |6    | 7     |   8  |        9 |
| ---  | ---    |   ---   |   ---   |  ---     | --- | ---  |  ---  |   ---    |     ---   |
|Possible σ's |    CV  | + CVC  |  +V  | +VC   |   +CCV  |   +CCVC  | +CVCC  |+VCC   | +CCVCC | 
[Order of syllable structure acquisition in Dutch (Levelt et al 2000)]

#  OT constraints on syllables
-   There are two major constraints:
    - <span style="font-variant:small-caps;">Onset</span>:      Assign one violation for every syllable lacking an onset.
    - <span style="font-variant:small-caps;">NoCoda</span>: Assign one violation for every syllable with a coda.
    -   The mirror-image constraints - <span style="font-variant:small-caps;">NoOnset</span> or <span style="font-variant:small-caps;">Coda</span> - aren't in CON.
-   Let's calculate the factorial typology.
    - Four constraints
        - (1) <span style="font-variant:small-caps;"> Onset   (2) NoCoda  (3) Max-C  (4) Dep-V </span>
        - How many possible rankings?
        - Let's enumerate them.
    - Let's try a few rankings…
    - Four inputs:
        - /V/
        - /CV/
        - /CVC/
        - /VC/
    - Four candidates per input: 
        - a. /V/      
        - b. /CV/     
        - c. /CVC/    
        - d. /VC/
    - Are any candidates harmonically bounded?
- Let's test our factorial typology using software (OT-Help)

# Complex margins
-  "margin" = onset or coda (i.e., anything except a nucleus)
- An onset or coda is said to be "complex" if it contains more than one consonant.

|Langauge | Complex onsets | Complex codas  | Possible syllables (partial list)|
|---|---|---|---|
|Cairene Arabic, Mokilese, Thargari, Cuna  |  forbidden |  forbidden  | CVC
|Klamath, Finnish, Tunica, Tamazight Berber | forbidden  | optional   | CVC CVCC
|Sedang, Spanish, Dakota, Italian  |  optional   | forbidden |  CVC     CCVC
|Totonac, English, Nisqually, Gilyak | optional   | optional  |  CVC CVCC    CCVC    CCVCC | 
[Typology of complex margins from Blevins (1995)]

-   What's missing?
-   Phonologists have proposed…
    - <span style="font-variant:small-caps;">*ComplexOnset</span>: Assign one violation per complex onset (with >1 consonant)
    - <span style="font-variant:small-caps;">*ComplexCoda</span>: Assign one violation per complex coda (with >1 consonant)
- …or just <span style="font-variant:small-caps;">*Complex</span>: Assign one violation per complex margin (onset or coda)
- Again, there are no constraints such as <span style="font-variant:small-caps;">OnsetsAreComplex</span> or <span style="font-variant:small-caps;">CodasAreComplex</span>.

# Recap of important ideas
- The syllable and its structure
- Why have syllables in our model if we can't really hear them?
- The sonority scale and syllables
- Syllable structure typology
- How to do factorial typology

