Title: Assignment 4: OT analysis of Spanish
Author: Brian W. Smith
Date: 9/7/2019
CSS: bws.css

<!-- Standard header. Change title in metadata -->

[USC Advanced Undergraduate Phonology](401_guide.html) ✳︎ Fall 2019 ✳︎ Smith
***

<div class="title">

[%title]

</div>

<!-- {{TOC}}-->

<!-- Content starts below -->

# Goals
- to develop, present, and argue for an OT analysis for a ddata set.

# Data
- Consider the distribution of voiced stops [b, d, g] and continuants [  ð ɣ] in the following data.

|IPA|gloss|
|---|---|
bastante	|'plenty'
brinkar		|'to jump'
berðe		|'green'
futbol		|'soccer'
sombra		|'shade'
uβa			|'grape'
karβon		|'coal'
suβo		|'I climb'
uβo			|'there was'
saβino		|'cypress'
kaβe		|'it fits'
kluβ		|'club'
deðo		|'finger/toe'
droɣas		|'drugs'
komuniðað	|'community'
seða		|'silk'
ganaðo		|'cattle'
usteð		|'you (sg. polite)'
gastos		|'expenses'
gonsales	|a surname
alɣo		|'something'
jaɣa		|'sore, boil'
aɣrio		|'sour'
gustar		|'to please'
xweɣo		|'game'
alβondiɣas	|'meatballs'

#Guidelines
- Write up your analysis in the form of a short paper, with introduction, numbered sections, numbered examples, and conclusion. Follow the advice about analysis and writing in Chapters 2 and 3 of Doing OT.
- Your target audience is someone who knows the mechanics of OT but does not have access to the Spanish data.
	+ You must justify crucial rankings and illustrate generalizations using relevant data.
	+ You don't need to include all of the data above in your paper, but make sure you include data that's relevant.
- Your write-up will include:
	- A descriptive generalization about the distribution of the voiced stops [b, d, g] and their fricative counterparts [β, ð, ɣ]:
		- Discuss their distribution (e.g. full contrast, allophonic variation, positional neutralization, etc.)
		- Explain what diagnostic(s) led to your conclusion about their distribution.
	- An OT analysis:
		- Propose a constraint set, using constraints from class or the readings when possible.
		- Define every constraint explicitly.
		- Use features to charaterize context-free or context-sensitive segmental markedness constraints. Make your featural assumptions clear. 
		- Provide all of the crucial rankings possible for your constraints.
		- Establish **crucial rankings** through pairwise winner/loser comparisons.
		- Support your analysis with (at least) summary tableaux for [kaβe] and for [gustar].
		- Make sure your analysis is consistent with Richnes of the Base, and show that the correct outputs obtain regardless of whether URs contain voiced stops or continuants.
	- Discussion of any feasible alternative OT analyses.
