Title: Daily schedule for Ling 531A
Author: Brian W. Smith
Date: 8/13/2019 to present
CSS: bws.css

<!-- Standard header. Change title in metadata -->

[USC Graduate Phonology](531_guide.html) ✳︎ Fall 2019 ✳︎ Smith
***

<div class="title">

[%title]

</div>

{{TOC}}

<!-- Content starts below -->

See the [syllabus](531_syllabus.html) for a full list of scheduled readings, but please remember that we may deviate from the original schedule.

<div class="syllabus">

- Wed 8/28
	- Handouts
		- [Syllabus](531_syllabus.html)
		- [Course overview](531_0.html)
		- [Generative phonology and phonemic analysis](531_1.html) (we made it up to the last section)
	- Comments
		- Consider attending [PhonLunch](https://dornsife.usc.edu/labs/usc-phon/fall-2019/) if you're interested in phonetics and phonology.
			- The first meeting is Thursday 12-1pm in the Conference Room.
	- To do for next time
		- This week there's a lot to do!
		- Join Slack
			- Post an introduction (as short as you'd like) in #introductions
			- Post a short comment or question on one of the readings in #papercomments
		- [Assignment 1](531_HW1.html) due on 9/4
		- Read Zsiga (2013) Ch 10–11
			- Focus on: 10-10.3, 11.2
		- Read Zsiga (2013) Ch 12-13
			- Focus on 12-12.2.1, 12.3, 13.3 
- Wed 9/4
	- Handout
		- [Generative phonology and phonemic analysis](531_1.html)
		- [Rules, features, abbreviations](531_2.html) (sections 13 and 15 weren't covered in class, and are included for your interest)
	- Comments 
		- [Assignment 1](531_HW1.html) due today
	- To do for next time
		- Read Doing OT Ch 1
			- Focus on Ch 1–1.2 (pp. 1-13)
			- This contains a discussion of Kisseberth (1970), which is worth rereading after Kisseberth (1970).
		- Read Kisseberth (1970)
			- Some notes and questions to keep in mind:
			+ 'trilateral cluster' = CCC
			* p. 300: the point of the discussion here is to determine whether the [a] is deleted or inserted
			* The rule in 10' is a typo. What should it be?
			* What is Kisseberth’s argument for why the standard theory is wrong to say that “there is no other way in which rules can be the ‘same’ except structurally” (p. 293)? What do you think of his argument?
- Wed 9/11
	- Handout 
		- [Rules plus constraints](531_3.html)
		- [HW write-up tips](531_HW_tips.html)
	- To do for next time
		- [Assignment 2](531_HW2.html) due on 9/18
		- Read Doing OT, Ch 1.3-1.8
- Wed 9/18
	- Handout 
		+ [Architecture of OT](531_4.html) (we finished it, except for the practice problem with Dutch)
	- Comments
		- [Assignment 2](531_HW2.html) due today
	- To do for next time
		- Assignment 3 due on 9/25
			+ This goal of this set of problems is to provide practice with OT reasoning.
			+ You do **not** have to write the solution as a short paper.
		- E-mail me your language for [Language data presentations](531_ldp.html) before 9/27 
- Wed 9/25
	- Handout 
		+ [Architecture of OT](531_4.html) (we did the practice problem for Dutch)
		- [Ranking constraints](531_5.html) (we finished it)
	- Comments 
		- Assignment 3 due today
	- To do
		+ Two readings that will help with your presentations. You needn't post a comment.
			- Read Doing OT Ch 3
				+ You can skip 3.3 for now
			- Read Doing OT Ch 2.1
		- We'll discuss the Steriade reading and the rest of Chapter 2 on 10/2 and 10/9.
		- E-mail me your language for [Language data presentations](531_ldp.html) before 9/27
		- [Language data presentation](531_ldp.html) on 10/2
- Wed 10/2
	- Language data presentations
	- Handout
		+ [Contrast in OT](531_6.html) (We made it through the section on complementary distribution)
	- To do for next time
		- [Assignment 4](531_HW4.html) due on 10/9
		- Read Doing OT Ch 2-2.7, 3.3
			* Section 2.5 is skippable.
			* Section 2.8 discusses Richness of the Base (RotB), also covered in the Steriade reading. If you're still confused about RotB after the Steriade reading, I recommend reading 2.8.
			* Incorporate all advice about doing an OT analysis into your assignment writeup.
		+ Read Steriade (2007)
			* Sections 7.5 and 7.6 are skippable.
		- You **must** post a comment on one of these before 10/9 if you haven't already.
- Wed 10/9
	- Handout
		+ Learning handout (physical handout)
		- [Contrast in OT](531_6.html)
		- Backup: [Syllable typology in OT](531_7.html)
	- Comments
		- [Assignment 4](531_HW4.html) due today
	- To do for next time
		- [Assignment 5](531_HW5.html) due on 10/16
		- Read:
			- Doing OT Ch 5
			- Lombardi (1999/2004) on assimilation
				+ note: Lombardi assumes a privative voice feature, which means voiced segments have [voice] and voiceless segments have *no voice feature*
			- If you'd like to review RCD or ERC fusion, read DOT Ch 2.10-2.12
- Wed 10/16
	- Handout 
		+ [Syllable typology in OT](531_7.html)
		+ Revising faithfulness: correspondence theory
	- Comments
		+ [Assignment 5](531_HW5.html) is due today
	- To do for next time
		- [Assignment 6](531_HW6.html) due on 10/23
		- If you'd like to review Correspondence Theory or positional faithfulness, read Doing OT Ch 4.6
- Wed 10/23
	- Handout 
		- [Assignment 6](531_HW6.html) is due today
	- Comments
	- To do for next time
		- Term paper topic deadline is 11/13
- Wed 10/30
	- Handout 
	- Comments 
	- To do for next time
		- Assignment 7 due on 11/6
		- Term paper topic deadline is 11/13
- Wed 11/6
	- Handout 
	- Comments 
		- Assignment 7 is due today
	- To do for next time
		- Term paper topic deadline is 11/13
		- Paper proposal due on 11/20
- Wed 11/13
	- Handout 
	- Comments
		- Term paper topic deadline
	- To do for next time
		- Paper proposal due on 11/20
- Wed 11/20
	- Handout 
	- Comments
		- Paper proposal due today
	- To do for next time
		- Term paper presentations on 12/4
- Wed 11/27
	- **No class**
- Wed 12/4
	- Term paper presentations today
	- To do for next time
		- Term paper due on 12/13
</div>
