Title: Language data presentations
Author: Brian W. Smith
Date: 9/14/2019
CSS: bws.css

<!-- Standard header. Change title in metadata -->

[USC Graduate Phonology](531_guide.html) ✳︎ Fall 2019 ✳︎ Smith
***

<div class="title">

[%title]

</div>

{{TOC}}

***

<!-- Content starts below -->

**In class presentations on 10/2/2019**
<div class="boring">

# Guidelines
- In this presentation, you will:
    - present a set of data that supports claims about the phoneme inventory of a language and that demonstrates an allophonic alternation;
    - present your own rule-based analysis of the allophonic alternation. 
- You must provide printed handouts or slides for your presentation (6 copies).
- You will have 12-15 minutes for your presentation followed by up to 5 minutes for discussion.
- For your presentation, you should not collaborate with other students in the class.
- Each of you will develop a data set for a different language. 
- You must present on a language you haven't previously worked on.[^Let's say you've previously worked on a language if you've written a paper (term paper, independent study, article, etc.) on the language. You *can* write your final paper for this class on the language you choose for your language data presentation.]
- Please email by noon on Friday, September 27 to let me know which language you propose to present on.

# Data sources
- Sources of language data include: 
    - descriptive grammars
    - descriptive journal articles
    - consultation with native speakers of the languages
    - introspection on a language for which you have native command
- Whichever source(s) you use should be cited at the appropriate point (e.g. "Johnson 2008") with the full reference list provided at the end of your handout.
    + If you consult a native speaker or use introspection, you must explain how collected data.
- Note: Wikipedia is *not* an adequate source. You must use vetted scholarly sources.


# Topics
- Your presentation should cover the following topics.
- Language background
    - the name of the language you are describing
    - the family to which it belongs
    - where it is spoken
    - the approximate number of speakers
- Inventory
    - An inventory of the phonemes of the language.
        - Present the vowel and consonant inventories separately. 
        - Arrange phonemes in columns according to place of articulation and in rows according to manner of articulation. 
        - Use IPA symbols to represent the phonemes. This may require translating the symbols used in your source into the IPA.
    - Support your proposed phoneme inventory with minimal pairs or near-minimal pairs, and include glosses. 
        - At a minimum, give (near-)minimal pairs for neighboring segments.
        - For example, if the language has /k, g, x, ɣ/, give minimal pairs for /k/ ~ /g/, /k/ ~ /x/, and /g/ ~ / ɣ/. 
        - If you can't find a (near-)minimal pair for a given opposition, discuss why you nevertheless posit a contrast. 
        - Be sure to include minimal pairs for both consonants and vowels. 
        - If tones are phonemic, include supporting evidence for that as well.
- Allophonic alternation
    - Describe at least one allophonic alternation in the language under study. 
    - Give example words showing the alternations, and, as appropriate, where the alternations do not occur. 
    - Discuss the contexts in which the different alternants are found and choose one as basic, justifying your decision. 
    - Where relevant draw on evaluative criteria such as simplicity and phonetic naturalness.
    - Formulate a rule (or rules) to characterize the alternation using features and rule ordering as appropriate. Provide derivations to illustrate the workings of your account.
</div>

