Title: Assignment 5: Factorial typology
Author: Brian W. Smith
Date: 10/2/2019
CSS: bws.css

<!-- Standard header. Change title in metadata -->

[USC Graduate Phonology](531_guide.html) ✳︎ Fall 2019 ✳︎ Smith
***

<div class="title">

[%title]

</div>

<!-- {{TOC}}-->

<!-- Content starts below -->
# Typology of nuclei
-	The table below shows which sounds can be syllable nuclei in various languages.
-	Some cells have (no) and (yes) in parentheses. These mean the language doesn't have these sounds, so we can't be sure. But I've filled them in with the values we'd expect them to have, based on the typology. Treat them as 'no' and 'yes'. 

|Language|	non-high vowel e.g. [a]	| high vowel e.g. [i]	| rhotic e.g. [r]	| lateral e.g. [l]	| nasal e.g. [m]	| fricative e.g. [s]	| stop e.g. [t] |
| --- |--- |--- |--- |--- |--- |--- | 
| Kabardian 		| 	yes	| no	| no	| no	| no	| no	| no | 
| Hawaiian			| yes		| yes	| (no)	| (no)	| no	| (no)	| no| 
| Sanskrit			| yes		| yes	| yes	| no	| no	| no	| no| 
| Lendu	|yes			| yes		| yes	| yes	| no	| no	| no| 
| English			| yes		| yes	| yes	| yes	| yes	| no	| no| 
| Central Carrier	| yes		| yes	| (yes)	| (yes)| 	yes	| yes	| no| 
| Imdlawn Tashlhiyt Berber	| yes | yes	| yes		| yes		| yes| yes| yes| 

-	Below is the sonority scale. Sounds at the left end of the scale are more sonorous than sounds on the right end. 'Sonorous' rough means 'more vowel-like.' 
	-	non-high vowel > high vowel > rhotic > lateral > nasal > fricative > stop

# Requirements
-	Write a short paper that:
	-	1. States a generalization about the possible patterns of nuclei across languages, identifying patterns that are logically possible but unattested patterns. Your generalization might make use of the sonority scale, and should be formulated to be as broad and general as possible.
	- 2. Proposes a set of constraints that produces the patterns in the table above, and doesn't produce patterns that are missing.  It's very important to show that your set of constraints succeeds at predicting attested patterns, and explain why it doesn't predict unattested patterns. (You might show how it fails for one attested pattern, and explain what that unattested pattern has in common with others.)
	- 3. Discusses at least one alternative constraint set or set of assumptions. Show how the typological predictions would change if your analysis were changed in some way. (The alternative should be as reasonable as possible.)
- Make sure you clearly explain the pattern and how your analysis works. 
	- Define all constraints clearly.
	- Clarify all assumptions that differ from those we've talked about in class.
	- Include an introduction and conclusion. 
	- Write this paper as if you were explaining your work to a classmate who is seeing the data for the first time, and understands OT as well as you do.

-	Inputs and candidate set
	-	For simplicity, assume the inputs are a single sound.
		-	/a/ /i/ /r/ /l/ /m/ /s/ /t/
		-	For each input there are two possible candidates
			- 1. Adding a vowel, e.g. [mə]
				- You can write use the diacritic [ ̯ ] to represent a vowel that is an onset or coda: [a̯ə] or [i̯ə]
				- If you're curious, these would sound like a glide followed by [ə]. In particular, [i̯ə] would sound like [jə].
			- 2. Syllabifying the sound as a nucleus, e.g. [m̩]
				- You can use the diacritic [ ̩ ]  to represent a consonant that is a nucleus: [m̩]
				
-	Constraints
	-	You're going to need a constraint against epenthesis, like DEP-V
	-	You're going to need constraints against nuclei with different manners of articulation. 
	- As a starting place, consider the constraint: 
		- *NUC/STOP. Assign one violation for every nucleus that is a stop.

# Advice

- In your analysis, you should do whatever it takes to capture the typology. 
	- This may require breaking or revising previously established assumptions. 
	- Simply make it clear when you do so. If you break established assumptions in your analysis, discuss (briefly) the ramifications of doing so.
- Depending on the assumptions you make in your analysis, you may be able to use OT-Help to evaluate the typological predictions of your constraint set.





 


