Title: Rules, features, and abbreviations
Author: Brian W. Smith
Date: 8/30/2019
CSS: bws.css
HTML header:	<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

<!-- Standard header. Change title in metadata -->

[USC Graduate Phonology](531_guide.html) ✳︎ Fall 2019 ✳︎ Smith
***

<div class="title">

[%title]

</div>

{{TOC}}

***

<!-- Content starts below -->

>The rules of the grammar operate in a mechanical fashion; one may think of them as instructions that might be given to a mindless robot, incapable of exercising any judgment or imagination in their application. Any ambiguity or inexplicitness in the statement of rules must in principle be eliminated, since the receiver of the instructions is assumed to be incapable of using intelligence to fill in gaps or to correct errors.
> 
> – Chomsky & Halle (1968: 60)

# The Sound Pattern of English (SPE)
- SPE: Chomsky & Halle's (1968) book *The Sound Pattern of English*.
	+  Proposes a framework that generates mappings via **rule-based derivations**.
- Algorithmic computation: the central goal of SPE is to develop **fully explicit algorithms** which generate all and only the surface forms of a language.
	- A fully explicit algorithm is a description of a process that can be carried out in a finite amount of time on a computational device.
		- See the quote at the top of this handout.
		- If the algorithm could be implemented in a modern programming language, it meets this requirement.
	+ When multiple algorithms are possible, formal simplicity dictates the best one.

# Anatomy of an SPE-style rule
- Rewrite rules take the form X ➔ Y / A ＿ B
	+ Transforms A**X**B into A**Y**B
	+ "X becomes Y when it's between A and B"
- Rules have the following parts.
	- Target / focus (X)
	- Structural change (Y)
	- Context (A＿B)
	- Structural description (AXB)
		- Describes the structure necessary for the rule to apply
- The environment may contain sounds that aren't adjacent to the focus.
	+  For example: X ➔ Y / A B C ＿ D E F
	+  Transforms ABC**X**DEF into ABC**Y**DEF
- Here are some examples, including some with features and other conventions you may have seen (#, ]~X, Ø, C, V).

|:---:|
| Ø ➔ i / C＿C|
| [+high] ➔ Ø / [–voice] ＿ [–voice]|
| [+consonantal] ➔ [–voice] / ＿ #|
| [–sonorant] ➔ [–voice] ∕ ＿ ]~wd|
| C ➔ [+voice] / V ＿ V|
| [-sonorant] ➔ [–voice] ∕ [–voice] ＿|
[Rule examples]

+ An important skill is being able to translate a rule into prose (and back again). Here are some tips and pitfalls for stating rules in prose:
	+ Give rules helpful and descriptive names.
	+ Be as unambiguous as possible.
		* The best way to test this is to show the prose to others and see if they can reconstruct the rule.
		* If the prose can be translated into notation and back again without loss, you've achieved a perfectly unambiguous description of the rule.
		* Sometimes a rule can't fruitfully be translated into prose, and needs to be paraphrased. Make this clear if you need to do it.
	+ "Precedes" implies "immediately precedes", but is still possibly ambiguous. Same for "before", "after", etc.
	+ "Between A and B" implies A_B, but is still possibly ambiguous.
	+ It's a good idea to use phonetic terms instead of features. For example, "An obstruent becomes voiceless at the end of a word" instead of "A [-sonorant] segment becomes [-voice] at the end of a word". Features vary quite a bit.
	+ "Left" and "right" can be usefully unambiguous.
- Properties of the focus can be written under the underscore, but this is relatively uncommon.

![This rule deletes voiceless vowels between consonants](under_brackets_example.svg)

# Rule ordering
- Rules are ordered and applied in sequence.
	+ input ➔ rule 1 ➔ rule 2 … rule k ➔ output
		* The output of rule 1 serves as the input to rule 2.
	+ Rules are **extrinsically ordered**.
		* Extrinsic ordering means you can't determine the order of rules without looking at the mappings of the language.
		* This means that children need to learn the ordering of rules.
	- There are proposals for **instrinsic rule ordering**, determined by characteristics of the rules themselves, or by characteristics of the rules and URs.
	- How else could rules apply?
- Order matters -- but not always.
	+ Sometimes changing the order of two rules changes the output of the grammar, sometimes it doesn't.
	+ Let's consider what (if any) order of rules is necessary to account for the mappings below, and write out a derivation.
		* **Mappings**: /bɛt-d/ ➔ [bɛtəd], /ʤʌmp-d/ ➔ [ʤʌmpt], /fɪl-d/ ➔ [fɪld]
		* **Epenthesis Rule**: Ø ➔ ə / [+coronal] ＿ [+coronal]
		* **Devoicing Rule**: [-sonorant] ➔ [–voice] / [–voice] ＿
	+ There are five types of rule interaction. We'll discuss the first four at length later.
		* **Feeding**:  X feeds Y if  Y is applicable to some form only because the form has undergone X. (X creates an input for Y)
		* **Bleeding**:  X bleeds Y if Y is *not* applicable to some form because the form has undergone X. (X destroys an input for Y)
		* **Counterfeeding**: X is counterfed by Y if Y could've fed X, but X is ordered first, so it doesn't. (Y applies too late to feed X)
		* **Counterbleeding**: X is counterbled by Y if Y could've bled X, but X is ordered first, so it doesn't. (Y applies too late to bleed X)
		* …or order doesn't matter.
# The evaluation procedure in SPE
- SPE suggested a metric for the evaluation of a system of rules, arguing that grammars with fewer symbols better capture linguistic generalizations.
	- **Fact**: There's usually (always?) more than one analysis that works for the observed data.
	- **Problem**: How does the language learner choose one?
		- **Conjecture**: The language learner favors rules that are simple, and analyses with fewer rules; SPE defines "simpler" as "having fewer symbols."
	- **Corollary 1**: Rules with fewer symbols should be more widespread among the world's languages.
	- **Corollary 2**: A theory that can capture widespread rules or sets of rules with fewer symbols than it needs to capture rare rules or sets of rules is more likely to be a correct model of the learner.
	- Note that the evaluation procedure is for comparing analyses with the same empirical coverage.
		+ A helpful aphorism attributed to Einstein: "Everything should be made as simple as possible, but not simpler."
- Here is the evaluation procedure in the words of Chomsky and Halle (1968):
	+ "The "value" of a sequence of rules is the reciprocal of the number of symbols in its minimal representation." (p. 334)
	+ "[…] the number of symbols in a rule is inversely related to the degree of linguistically significant generalization achieved in the rule." (p. 335)
- When rules resemble each other in specific ways, this resemblance is a significant linguistic generalization which needs to be captured.
- Let's brainstorm some other measures we could use to compare rule-based systems.
- To help capture generalizations and minimize the number of symbols, SPE used both **phonological features** and **abbreviatory conventions** to combine rules.

# Phonological features
- In SPE, URs are built of **distinctive features**, and this is what the grammar manipulates.
- /kæt/ is really just an abbreviation for a sequence of three feature bundles. We write /kæt/ to preserve our sanity, but we really mean:

|k|æ|t|
|:---:| :---: | :---:|	 
|	–syllabic |	+syllabic | –syllabic |
|	–long | –long | –long |
|	+consonantal | –consonantal | +consonantal |
|	–sonorant | +sonorant | –sonorant |
|	–continuant | +continuant | –continuant |
|	–delayed release | | 	–delayed release |
|	–approximant |+approximant |–approximant |
|	–tap | –tap | –tap |
|	–trill | –trill | –trill |
|	–nasal | –nasal | –nasal |
|	–voice | +voice | –voice |
|	–spread glottis | –spread glottis | –spread glottis|
|	–constricted glottis | –constricted glottis | –constricted glottis|
|	–labial | –labial | –labial|
|	–round | –round | –round|
|	–labiodental |	–labiodental |	–labiodental|
|	–coronal |–coronal |+coronal|
|	–lateral |–lateral |–lateral|
|	+dorsal |–dorsal |–dorsal|
|	+high	|–high| | 
|	–low 	|+low | |
|	…	| … | … |
[Portions of the feature bundles of /k/, /æ/, and /t/, using the feature set of Hayes' (2009) textbook]

- There is quite a bit of variation in how features are used (see the reading Zsiga 2013 for some examples). 
	- We'll assume the feature set is universal and the same in every language.
	- We'll assume that features are binary: they are always + or –.
	- We'll also assume that every sound is specified for most features.
	- But not every sound is specified for every feature.
		+ For example, most consonants don't have features relating to tongue height like [high] or [low].
	- Disclaimers
		+ There are proposals with non-binary ("privative") features.
		+ There are proposals in which feature specifications are as minimal as possible, and all redundant/predictable features are added by rules. 
			+ For example, in a language without voiceless sonorants, sonorants don't need a [voice] feature if a rule makes [+sonorant] sounds [+voice].
		- There are arguments against feature being universal (more on this below).
- Features allow us to combine related-looking rules by referring to natural classes.
	+ A **natural class** is group of sounds in an inventory which share one or more distinctive features, to the exclusion of all other sounds in the inventory.
	+ These two rules of English…
		* n ➔ n̪ / ＿ θ
		* l ➔ l̪ / ＿ θ
	- …can be combined into one rule:
		+ [+coronal] ➔ [+dental] / _ [+dental]
		+ "A coronal becomes dental before a dental."
		+ This rule predicts that *any* [+coronal] sound will become [+dental] before *any* [+dental] sound.[^dental]
- In SPE-style rules, e.g. [+coronal] ➔ [+dental]…
	- Features in the focus mean: find a sound with the required features, in the required environment.
	- Feature in the change mean: make the specifed change.
	- The rule [+coronal] ➔ [+dental] / _ [+dental] does the following:
		- 1. find a sound that is [+coronal]
		- 2. if the [+coronal] sound is followed by a sound that is [+dental]
		- 3. change the [dental] feature of the [+coronal] sound to [+dental]

# How do we decide what the features should be?
- Phonologists have developed a more-or-less consensus set of features, based on the processes seen in languages.
- This is based on the assumption that features are innate and universal.
- Typical desiderata:
	- If two sounds are contrastive in some language, they must differ in at least one feature.
		- E.g., if tap [ɾ] and trill [r] are contrastive in Spanish,  we need a feature to distinguish them, like [trill].
	- If a group of sounds is targeted by a rule, they should be describable with a set of features.
		+ E.g., if we see a rule like {A, B, C, D} ➔ ... or ... / {A, B, C, D},
		- especially in more than one language, then {A,B,C,D} should be a natural class.
		- E.g., if lots of languages nasalize a vowel before a consonant with nasal airflow (like [m, n, ŋ]), then [+nasal] seems like a good feature.
		- E.g., the feature [+strident] picks out the set of sounds that trigger epenthesis in the English plural [s, z, ʧ, ʤ, ʃ, ʒ]. Without [strident], these sounds wouldn't form a natural class.
	- A feature should correspond to some phonetic property.
		- Most are articulatory, but they can be acoustic too.
- A different view is that feature systems are neither innate nor universal.
	- The language learner discovers his/her language's feature set during the course of language learning via exposure to ambient language patterns.
	- As a result, a sound shared by two languages could have different features in each language.
	- A typological survey in Mielke (2007) finds that existing feature systems can only account for about 70% of rule-targetting classes in natural languages.
	- There are many "unnatural" processes that refer to disjointed sets of sounds.
		+ For example, consider this pattern from Kolami (Mielke 2011 citing Emenau 1961).[^mielke]
			* Allomorph [-l] after / ʈ ɖ n̪ i iː e eː a aː / 
			* Allomorph [-ul] after / p t̪ k d̪ g s z m ŋ j /

# Commonly used features worth knowing
- You do *not* need to memorize these.
- **Voicing features**
	+ [voice]: voiced sounds are +
	+ [spread glottis]: aspirated sounds are +
	+ [constricted glottis]: glottalized/creaky voice and ejectives are +
- **Manner features**
	- [syllabic]: vowels and syllabic consonants are +
	- [consonantal]: vowels and glides are –
	- [sonorant]: obstruents (non-nasal stops, fricatives, affricates) are –
	- [continuant]: fricatives and approximants are +
		+ Nasals are [–continuant]!
	- [nasal]: nasals are +
	- [lateral]: laterals are +
	- [delayed release]: affricates are +
- **Major place features**
	- [labial]: lips are active articulator (e.g., bilabial, labiodental)
	- [coronal]: tongue tip/blade/front is active articulator (e.g., dental and alveolar, retroflex, palatal)
	- [dorsal]: tongue body/back is active articulator (e.g. palatal velar, uvular)
	- [pharyngeal]: tongue root is active articulator 
	- [laryngeal]: "glottal" sounds, e.g. [h] and [ʔ]
- **Vowel features**
	+ [high]
	+ [low]
	+ [front]
	+ [back]
	+ [ATR], [tense]
		+ [i e u o] are [+ATR] or [+tense]
		+ [ɪ ɛ ʊ ɔ] are [+ATR] or [+tense]
		+ Low vowels depend on the feature system.
	- Most feature systems use vowel features to differentiate [+dorsal] consonants, in addition to using them for vowels.
- The class materials contain a few different feature charts, if you're curious to see how they differ.
	+ Elisabeth Zsiga's (2013) Phonetics and Phonology feature chart.
		* Place features are privative, but other features are binary.
	+ Bruce Hayes' (2009) Introductory Phonology feature chart.
		+ Covers nearly every soound in the IPA, including secondary articulations.
	+ Jason Riggle's (2008) feature chart.
	+ A feature chart for SPE, typeset and commented by Ewan Dunbar.

# Abbreviatory conventions
- Rules can also be combined using **abbreviatory conventions**. Here are four of the most common:

![Braces such as {X,Y} mean "either X or Y"](braces_example.svg)
	
![Braces can go around any part of a rule.](braces_example_2.svg)

![Parentheses such as (X) mean "one or zero X"](parens_example.svg)

![Subscripts such as X~Y mean "Y or more Xs". You can provide an upper limit with a superscript.](C0_example.svg)

![Lowercase greek letters are variables that must match](alpha_example.svg)

- Each of the rules above is **expanded** into **sub-rules** in pre-defined ways. Here are some made-up examples, some of which are a bit strange.
	+ C ➔ Ø / ＿ {C, #}
		+ First, try C ➔ Ø / ＿ C.
		+ Second, try C ➔ Ø / ＿ #.
	+ C ➔ Ø / ＿ (C)C
		+ First, try C ➔ Ø / ＿ CC.
		+ If the first sub-rule didn't apply, try C ➔ Ø / ＿ C.
	+ C ➔ Ø / ＿ C<sup>5</sup><sub style='position: relative; left: -.5em;'>0</sub>
		- First, try C ➔ Ø / CCCCC ＿
		- If it didn't apply, try C ➔ Ø / CCCC ＿
		- If it didn't apply, try C ➔ Ø / CCC ＿
		- If it didn't apply, try C ➔ Ø / CC ＿
		- If it didn't apply, try C ➔ Ø / C ＿
		- If it didn't apply, try C ➔ Ø / ＿
	- C ➔ [αnasal] / ＿ [αnasal]
		+ Apply these two sub-rules simultenously:
			* C ➔ [+nasal] / ＿ [+nasal]
			* C ➔ [–nasal] / ＿ [–nasal]
	- C ➔ [αnasal] / ＿ [–αnasal] 
		+ Apply these sub-rules simultenously:
			* C ➔ [+nasal] / ＿ [–nasal]
			* C ➔ [–nasal] / ＿ [+nasal]
	- C ➔ [αnasal, βvoice] / ＿ [αnasal, –βvoice]
		+ Apply these sub-rules simultenously:
			+ ɑ+, β+: C ➔ [+nasal, +voice] / ＿ [+nasal, –voice] 
			+ ɑ–, β+: C ➔ [–nasal, +voice] / ＿ [–nasal, –voice]
			+ ɑ+, β–: C ➔ [+nasal, –voice] / ＿ [+nasal, +voice]
			+ ɑ–, β–: C ➔ [–nasal, –voice] / ＿ [–nasal, +voice]
+ Let's see abbreviatory conventions in action using the following example from SPE (p. 339, adapted slightly). Consider a fictional language in which:
	* / i / and / j / are actualized as [ j ] before / p r j a /.
	+ / w / and / u / are actualized as [ u ] before / p r j a /.
	+ Let's assume this fictional language has the same consonants as English and five vowels: / i e a o u /.
- At first glance, it looks like we need 8 rules, but we can use braces, features, and trickery to reduce this down to *just one rule*.  [Solution at the bottom.][Solution]

![Eight rules](rule0.svg)

- Although it may seem needlessly complex, being able to combine these rules is (probably) a good thing: whenever we have different rules that seem to be doing the same thing, we want to be able to combine them.

# A real example from SPE

- The fictional example is far from the most complex rule in SPE.
	- Rules like the vowel tensing rule below have many sub-rules, capturing a complicated set of requirements for application.
	- Without abbreviatory conventions, SPE would have many, many more rules for vowel tensing.
	- Since rule simplicity plays a pivotal role in the evaluation of grammars, the effect of abbreviatory conventions in reducing rules’ structure is a good result.

![One of the five vowel tensing rules from SPE (p. 242). [FB] and [seg] are features used for boundaries.](SPE_tensing_rule.png)

![Just the top part (rule 30 in SPE Ch. 3)](SPE_tensing_simple.png)

- The top part of this rule expands into the sub-rules:
	+ Sub-rule #1: V ➔ [+tense] / ＿ V
	+ Sub-rule #2a: [+low, +stress] ➔ [+tense] / _ #
	+ Sub-rule #2b: [–low, +stress] ➔ [+tense] / _ #
	+ Sub-rule #2c: [–low, –stress] ➔ [+tense] / _ #

- Let's think about the predictions of this rule for the vowels below.

|Vowel|Tense|Low| |Vowel|Tense|Low|
|:---:|:---:| :---: |:---:|:---:|:---:|:---:|
|i	|	+| –| |u	|	+| –|
|ɪ	|	–| –| |ʊ	|	–| –|
|e	|	+| –| |o	|	+| –|
|ɛ	|	–| –| |	|	 |  |
|æ	|	–| +| |ɑ	|	+| +|
[English vowel features]

- After tensing applies, another rule reduces unstressed lax vowels to [ə].

# Some potential issues
- As a theory of possible phonological alternations, SPE is possibly too powerful.
	- Consider the prediction from [above][theevaluationprocedureinspe]: Rules with fewer symbols should be more widespread among the world’s languages.
	- It's quite easy to write two rules with the same number of symbols, where the process captured by one rule is very common and the processed by the other rule is very rare.
		- For example: word-final devoicing (very common across the world's languages) and word-final voicing (very rare across the world's languages).
	+ In fact, nearly any phonological process can be generated using rules. 
- There are sometimes related-looking rules that can't be combined using abbreviatory conventions.
	+ We're failing to capture a generalization.
	+ We'll consider these next when we talk about conspiracies.

# The defining characteristics of SPE 
- The following are major characteristics of the SPE research program, many of which set it apart from earlier work.[^goldsmithlaks]
	+ Generative grammar, URs and SRs:
		+ SPE is a model of mappings between URs and SRs.
	- Fully explicit algorithms:
		- The goal is to generate all and only the mappings of a language.
		+ Formal simplicity dictates the best analysis, and is achieved using features and abbreviatory conventions.
	+ The SRs of a language are generated via a sequence of phonological rules.
		- input ➔ rule 1 ➔ rule 2 … rule k ➔ output
		- A priority for the phonologist is to determine -- to the greatest extent possible -- the ordering of rules.
	- Features: 
		- In SPE, representations are linear sequences of feature bundles. 
		+ They contain nothing more -- not even syllables.
		+ Later work in phonology proposed richer representations, containing syllable structure, autosegmental features, metrical feet, moras, etc.
	- More abstractness: 
		- In SPE, there are fewer limitations on proposing underlying segments. 
		- Analyses may contain URs that differ substantially from SRs, even containing segments that never appear on the surface, giving more **abstract URs**.
		+ For example, to account for stress, SPE proposes a distinction between final /ss/ (in *caress*) and final /s/ (in *Paris*) (p. 151).
- These differences are why Chomsky and Halle (1968) distance themselves from earlier work and explicitly avoid the terms *phoneme* and *allophone* (p. 11, p. 65). Earlier work in the Structuralist program…
	+ … uses unordered "taxonomic" rules such as "Phoneme A is realized with variant B in context X––Y".
		+ In SPE, rules are ordered, apply in sequence, and are defined as algorithms.
	+ … has rigid requirements for positing phonemes, such as the requirement that every phonetic representation has a unique phonemic representation, and the requirement that the set of phonemes be as small as possible.
		* In SPE, the goal is to construct a model that generates the correct surface forms, and a UR is justified so long as it explains some data.
	- From this point on, we'll rarely see the terms *phoneme* and *allophone*. 
		- We'll often talk about sounds in URs and sounds in SRs. 
		- You should feel free to use *phoneme* and *allophone*, since it's clear that you don't intend the terms in the pre-1950s sense.
 	
# Recap of major ideas
- The Sound Pattern of English
- explicit algorithm
- rules and rule ordering
- distinctive features
	- natural class
	- desiderata for features
- rule formalism
	+ target / focus
	- structural change
	+ environment
	+ structural description
- the evaluation procedure in SPE
+ abbreviatory conventions \(\), \{\}, C~n, Greek letter variables
- abstract URs

# Practice problems

- Imagine a language that has the inventory shown below.
	- Nine of the circled sets of sounds are natural classes.
	- Describe each class in terms of distinctive features, using only the features defined in this handout. 
	- Use as few features as possible to uniquely identify each set relative to the whole inventory. 
	- Indicate the set that is not a natural class.
	- [ɻ] is a retroflex approximant.

![Practice problem from Zsiga (2013) Chapter 12](zsiga_practice.png)

- Translate the following rules from SPE-style notation to English.
	- [+syl, +high] ➔ [−voice] / [−voice, +cont] ＿  [−voice, +cont]
	- [+dorsal, −cont, −son, +voice] ➔ [+cont] / [+syl, +back] ＿  [+syl, +back]
	- [−son, +cont] ➔ [−cont] / ＿  #
	- [+voice, −cont, −son] ➔ Ø / [+nasal] ＿ #
	- [+syl, +low] ➔ [−low, +round] /  ＿ C~0 [+syl, +high, −back]
- Translate the following rules from English to SPE-style notation.
	- Nasals delete preceding fricatives, l, and r.
	- In a sequence of two (non-nasal) stops, the first becomes a fricative.
	- Voiceless stops and fricatives become voiced between sonorants.
	- [ɻ] becomes [l] preceding [l].
	- Mid vowels agree with the vowel of the preceding syllable in ATR value.
- Write a system of rules for /t/, capturing the distribution in the diagram, along with the generalizations below. Make the rules as minimal as possible.
	- /p/ and /k/ also aspirate before stressed vowels.
	- /d/ also becomes a tap between vowels.

![](tallphones.svg)

# Solution

![Eight rules](rule0.svg)

- We can create two rules using braces.

![Two rules](rule1.svg)
	
- There's still some similarities between the two rules not being captured. 
- Braces, features, and some other conventions reveal the similarities:
	
![Two rules with features](rule2.svg)
	
- Adding braces gives us one rule:
	
![One rule](rule3.svg)

- We could also obtain a single rule using lowercase Greek letters.

[^goldsmithlaks]: If you'd like to learn more about the historical context of the mechanisms of SPE, I recommend Goldsmith & Laks' (2012) Chapter "Generative Phonology: its origins, its principles, and its successors" in the *Cambridge History of Linguistics*. That is what I'm paraphrasing here.

[^dental]: [dental] isn't usually a feature, but is used here for simplicity.

[^mielke]: Mielke (2011) is an optional reading in the shared files for the course.