Title: Homogeneity of target, heterogeneity of process
Author: Brian W. Smith
Date: 10/12/2019
CSS: bws.css

<!-- Standard header. Change title in metadata -->

[USC Graduate Phonology](531_guide.html) ✳︎ Fall 2019 ✳︎ Smith
***

<div class="title">

[%title]

</div>

{{TOC}}

***

# When to posit new constraints
- When is it necessary to posit a new constraint?
- In what sense are ranking paradoxes symmetrical?
    - Consider the following two ERCS: 
        - <L, W, L> and <e, L, W>
        - What are ways a new constraint could resolve this paradox?
    
| -- | -- | -- |
|L  | W   | L  |
|e |  L    |  W |
  
# Justifying constraints
-	There are three ways to justify a constraint:
    - **Formal**: resembles other constraints in CON.
    - **Functional**: reflects articulation, perception, or memory.
        + Examples: Agree, Ident-Onset[Voice]
        + Potentially includes audience design
    - **Typological**: its cross-linguistic typological predictions are borne out.
- No matter how a constraint is justified, its addition to the constraint set makes predictions with respect to factorial typology that must be addressed.


# Crosslinguistic conspiracies: Homogeneity of Target, Heterogeneity of Process
- Phonological operations in different languages seem to be aiming for the same surface pattern (*target*), and achieving it in different ways (*process*).
    - McCarthy (2003) calls this **Homogeneity of Target, Heterogeneity of Process**
    - This is similar to -- but distinct from -- within-language conspiricies.
- Example: consider the typological predictions of the following constraint \*V[–voice]V along with the many faithfulness constraints we've discussed (Max, Dep, Ident[voice], Linearity).
    + What rankings determine *whether* the marked structure should be avoided?
    - What rankings determine *how* the marked structure should be avoided?
    - How does OT capture homogeneity of target?
    - How does OT capture heterogeneity of process?

# Austronesian \*um (Zuraw & Lu 2009)
- Example: cognate infixes in some Western Austronesian languages, from proto *um or *m (Zuraw & Lu 2009). 
- What constraint could be responsible?
- What faithfulness constraints are violated in each case?

| | Tagalog (Philippines)   | Timugon Murut (Indon.)  | Sarangani Blaan (Phil.)   | Palauan (Palau) |Limos Kalinga (Philippines) |
| -- | -- | -- | -- | -- | -- |
| p/f | pili, pumili  |   patoj, matoj   |  fati, mati  | --  | pija, kumija |
| t   | takbo, tumakbo |  tuun, tumuun   |  tiis, tmiis    | toŋakl, tmoŋakl | |
| s   | sulat, sumulat |   |   saloʔ, smaloʔ   | sisijʔ, smisijʔ  | |
| k/q | kuha, kumuha   |   |   kaan, kmaan | kiwt, kmiwt | kan, kuman |
| b/v/β   | bili, bumili |    bigod, migod  |  bunal, munal  |  basəʔ, masəʔ |    bali, ɡumali | 
| d/ð | datiŋ, dumatiŋ |  |    dado, dmado | ðakl, ðmakl | dakol, dumakol 
| ɡ   | ɡawa, ɡumawa  |   ɡajo, ɡumajo            | | | |
| labial later      | | | |          ðobəʔ, ðwobəʔ | |  


| | Acehnese (Indonesia) | Tjuabar Paiwan (Taiwan) | Toba Batak (Indonesia) | Kavalan (Taiwan) |
| -- | -- | -- | -- |
| p/f | paɟoh, sɯmaɟoh  | pajsu, pənajsu |  paddita, uppadita  |  paʁit, pmaʁit |
| t   | tulak, tɯmulak |  təkəɭ, təm(ə)kəɭ   |  tibbo, tumibbo |  tajta, tmajta |
| s   | saluɛn, sɯmaluɛn  |   supu, səmupu |    |     sum, smum |
| k/q | kalɤn, kɯmalɤn |   kan, kəman |  -- |  kiɾim, kmiɾim |
| b/v/β  |  --  | vəli, vənəli  |   balga, ubbalga |  βuɾa, uβuɾa |
| d   | dɯŋɤ, dɯmɯŋɤ  |   dapəs, dəmapəs |  deŋɡan, dumeŋɡan |    -- |
| ɡ   | ɡantoŋ, ɡɯmantoŋ   | |      ɡabe, ɡumabe |    -- |
| labial later | |       təvəɭa, tənvəɭa     | |    |
   
#  More cross-language conspiracies: \*NC (Pater 1999)
-   What's the constraint used in Pater (2009)?
-   Let's come up with rankings for the cases below:
-   These rules are attested in a variety of languages:
    - Post-nasal voicing  NT → ND   (Japanese, Puyo Pungo Quechua)
    - Nasal deletion  NT → T    (Kelanatan Malay, Swahili)
    - Denasalization  NT → TT   (Toba Batak, Kaingang, Mandar)  
    -  Nasal substitution  NT → N    (Indonesian, Kihehe)
+   A number of languages have multiple processes:
    - Modern Greek:   NT → ND, MPS → PS    
    - Karpathos Greek:    NT → ND, N#T → T#T   
    - OshiKwanyama:   NT →  ND, N#T → N 
    -  Kihehe:         NT →  N,  NS → S  
-   My contribution: *NC̥ blocks phrase-final devoicing in Dholuo
    - Dholuo:         D# → T#, ND# → ND#
-  Some rules. Why isn't this solution better?
    - Deletion:       [+nas] →  Ø  /   __ [-voice]
    - Epenthesis:         Ø  → V  / [+nas] __ [-voice]
    - Post-nasal voicing: [-son] →  [+voice]  / [+nas] __ 
    - Denasalization:     [+nas] →  [-nas] /  __ [–voice]

# Wrapping up
-   Ranking paradoxes require new constraints.
-   New constraints should be posited with care:
    - Clearly defined.
    - With an understanding of typological predictions.
    - Functional motivation is a plus.
-  We've seen a few examples of how to motivate a constraint typologically.
    - OT's ability to model "homogeneity of target; heterogeneity of target" follows from the assumptions that… 
        - CON is universal.
        - Languages differ with respect to their constraint rankings.
