Title: Assignment 7: Somali
Author: Brian W. Smith
Date: 10/30/2019
CSS: bws.css

<!-- Standard header. Change title in metadata -->

[USC Graduate Phonology](531_guide.html) ✳︎ Fall 2019 ✳︎ Smith
***

<div class="title">

[%title]

</div>

<!-- {{TOC}}-->

<!-- Content starts below -->

# Directions
- In this assignment, you'll write a paper which develops an Optimality Theoretic analysis of the data for which you developed a rule-based analysis in [HW 2](531_HW2.html). 
	- Note: your analysis will probably be unable to account for some of the data. This is discussed below.
	+ You *do not* need to provide a rule-based analysis.
	+ One way to organize the paper is to create a separate subsection for each alternation, but you should organize it however you feel is clearest.
	+ Since this is a paper, it's important that you provide enough explanation for a reader to follow your analysis and understand the data, and don't forget an introduction and conclusion. (Feel free to copy the structure of any of the papers or chapters we've looked at.)
- Explain each alternation as theory-neutrally as possible, providing generalizations using natural classes.
	- Assume your reader doesn't have access to the data. 
	+ A good generalization is (A) descriptive enough that it could be used to generate new data that are compatible with the pattern and (B) supported by relevant examples. (See Doing OT for more)
- For each alternation, posit markedness and faithfulness constraints that interact to produce the alternation.
	- Name and clearly define every constraint that you use. Define in the format "Assign one violation for every…" 
	- Try to use constraints from class or the readings (including the textbook), or relate your constraints to these if possible. Justify your constraint functionally if possible.
	- Constraints should be as general as possible, and should not include statements with "except when…" or "unless…", since those effects should come from constraint interaction.
- Present and justify all crucial rankings. You can (and should) use either comparative tableaux or combination tableaux for this. 
	- Whenever you present a tableau, walk the reader through the tableau, explaining the candidates you included, why the winner wins, and why the losers lose. See any of the readings for examples of this.
	- Any time you add an alternation and need to posit a new constraint, be sure to check the ranking of the new constraints with the ones you posited previously.
- Your analysis is probably going to fail to account for some of the patterns when you combine certain alternations into a single grammar.
	- This is especially true for alternations that required rule ordering in your original analysis.
	- If this happens, you must **show** that the analysis doesn't work (recall: ranking paradoxes andd harmonic bounding are the tools to show an OT analysis doesn't work). Simply asserting that the analysis doesn't work is not sufficient.
	- You should discuss why OT seems unable to account for the pattern: what about the alternation interaction is troublesome for the output-oriented OT model?  Try to characterize the problem as generally as possible.




 


