Title: Assignment 1: phonology practice problems
Author: Brian W. Smith
Date: 8/22/2019
Comment: for USC Ling 531A Fall 2019
CSS: bws.css

<!-- Standard header. Change title in metadata -->

[USC Graduate Phonology](531_guide.html) ✳︎ Fall 2019 ✳︎ Smith
***

<div class="title">

[%title]

</div>

<!-- {{TOC}} -->

***

<!-- Content starts below -->

# Goals
- to provide me with a baseline estimate of your experience with writing and linguistic argumentation
- to practice phonemic analysis and argumentation

# Instructions
- Posit and justify a phonemic analysis for all of the following data sets. For each data set, you will:
	- present the data (organized however you like)
	- propose a phonemicization
	- show how the data support your proposed phonemicization, e.g.:
		- “the segments [e] and [ɛ] are in a contrastive distribution, as indicated by the minimal pairs: ...”
		- “voiceless unaspirated and aspirated stops are in complementary distribution; the complementary environments in which they occur are as
follows..."
	- discuss any alternatives that are compatible with the data
	- argue for the phonemicization you went with
- The "optional challenges" are provided in case the assignment feels too easy.
- Assignment prompts are very prone to typos, so let me know via e-mail if you suspect one.
- Submit your completed assignment in hardcopy at the beginning of class on **September 4**.
	- You can format or typeset the paper however you like, as long as:
		- It's typed, including IPA characters.
		- It's as clear as possible. This is especially important for examples.
		- You leave margins and double space so I can add comments.
	- You are free to copy-paste the data from [this file](531_HW1.mmd).

# How to write it up
- For all of the assignments in this class, write up your solution as a short paper, including:
	- sections presented in a logical order (with section headings)
	- a very short introduction: something that outlines the content of the paper 
		- For this assignment, something like "this paper presents a phonemic analysis for three languages […] Language X displays contextually-limited contrast, Language Y displays […] Language Z […]" is sufficient.
	- a very short conclusion: repeating the introduction
- Imagine the audience is someone who hasn't seen the data and doesn't have access to the HW assignment prompt, but knows everything that we discussed in the first week.
	- This means you should present and explain the data in your writeup.
 
# Data set 1: Mokilese
- Provide a phonemic analysis of [i], [u], [i̥], and [u̥] in Mokilese, an Austronesian language spoken in Micronesia.
- The circle diacritic indicates that a sound is voiceless.
- **Optional challenge**: What, if anything, can we say about the other vowels given this data set?

|---|---|---|---|
|[pi̥san]	| 'my beard'	|[uduk] | 'white'|
|[dupu̥kda]	| 'chop it down'|[kask] | 'warm'|
|[pu̥ko]		| 'seed'	|[poki] | 'he is carrying it'|
|[ki̥sa]		| 'flea'	|[pil] 	| 'to dress'|
|[su̥pwo]	| 'hanging'	|[apid] | 'he stirred it'|
|[kamwɔki̥ti]	| 'sugar cane'	|[ludᴣu]| 'read'|


# Data set 2: Tojolabal
- Provide a phonemic analysis of [k], [k'], [t], and [tʰ] in Tojolabal, a Mayan language spoken in Mexico.
- [k'] is a glottalized voiceless velar stop, and [t'] is a glottalized voiceless alveolar stop.
- **Optional challenge**: also consider [t], for which data is sparse.
- **Optional challenge**: what does your analysis have to say, if anything, about [kʰ]?

|---|---|---|---|
|[kisim]	| 'my beard'	|[sak] 		| 'white'|
|[t͡sak'a]	| 'chop it down'|[k'iʃin] 	| 'warm'|
|[ʔinatʰ]	| 'seed'	|[skut͡ʃu] 	| 'he is carrying it'|
|[k'ak]		| 'flea'	|[k'uːtes] 	| 'to dress'|
|[p'akan]	| 'hanging'	|[snika] 	| 'he stirred it'|
|[k'aʔem]	| 'sugar cane'	|[ʔak'] 	| 'read'|
|[t͡sitam]	| 'pig'		|[t͡satatʰ] 	| 'another kind of plant'|
|[makton]	| 'a patch'	|[mutʰ] 	| 'chicken'|
|[potot']	| 'kind of plant'|[nahatʰ] 	| 'long'|
|[tinan]	| 'upside down'	|		| |

# Data set 3: Québecois French
- Provide a phonemic analysis of [ʀ] and [r] in French, as spoken in Québec.
- [ʀ] is used here to transcribe a voiced uvular fricative (not a trill).
- [r] is an alveolar trill.
- **Optional challenge**: if you wanted to further test your analysis, what data would be relevant, and how might you collect it?

|---|---|
|[puvwaʀ]	| 'power'	|
|[sypɛʀb]	| 'superb'	|
|[ʀenɔve]	| 'to do up'	|
|[ʀøgaʀde]	| 'to look at'	|
|[pøtɛtr]	| 'maybe'	|
|[tro]		| 'too many'	|
|[pøtɛtʀ]	| 'maybe'	|

