Title: Assignment 5: Recursive Constraint Demotion
Author: Brian W. Smith
Date: 10/2/2019
CSS: bws.css

<!-- Standard header. Change title in metadata -->

[USC Graduate Phonology](531_guide.html) ✳︎ Fall 2019 ✳︎ Smith
***

<div class="title">

[%title]

</div>

{{TOC}}

***

<!-- Content starts below -->

# Goals
- The goal of this assignment is to provide practice with crucial rankings, ERCs, ERC fusion, and RCD.

# Data
- The Lardil data provided via Slack.

# Guidelines
- Write a handout or slides showing the application of RCD step-by-step.
	- Terse, bullet pointed discussion is acceptable, as long as you do the following: 
	- First, make a comparative tableau and identify all crucial rankings for the Lardil data. 
		- You can use ERC fusion to provide crucial rankings.
		- State these as succinctly as possible, along with support.
		- Write a hasse diagram, and indicate any ranking information that cannot be represented with a hasse diagram.
	- Second, perform RCD by hand on the data provided.
		+ Show every step.
	- You can number or letter the constraints and candidates, and refer to them using these.
		+ I'm less interested in the content of the constraints or candidates, andd more interested in your ability to identify crucial rankings andd apply RCD.
	- Be sure to include a brief introduction and conclusion.
- Install OT-Help, OTSoft, or OTWorkplace (I can only provide tech support for OT-Help)
	+ Perform RCD using your preferred software program.
	+ Include the output of the software program, comparing it to the results of hand-applied RCD.
- In your slides or handout, briefly discuss at least two cases in which RCD ranks constraints which are not crucially ranked. Explain where this difference comes from.



