Title: Course overview
Author: Brian W. Smith
Date: 8/20/2019
CSS: bws.css

<!-- Standard header. Change title in metadata -->

[USC Graduate Phonology](531_guide.html) ✳︎ Fall 19 ✳︎ Smith
***

<div class="title">

[%title]

</div>

{{TOC}}

***

<!-- Content starts below -->

> It has been said that "all models are wrong but some models are useful." In other words, any model is at best a useful fiction—there never was, or ever will be, an exactly normal distribution or an exact linear relationship. Nevertheless, enormous progress has been made by entertaining such fictions and using them as approximations.
> 
> — Box & Luceño (1997)

# Course overview
- This course
	- In this course, we'll focus primarily on **Optimality Theory**, a framework that emerged in the early 1990s and replaced rules with constraints.
	- Here's the narrative of the class, which very roughly follows the recent history of generative phonology:
		- Phonology basics: some sounds vary depending on context - let's do phonemic analysis to discover how.
		- Generative phonology: let's build a model with rules and features.
		- Problem: rules fail to capture some data.
		- Solution: let's add constraints!
		- Problem: rules and constraints together are difficult to formalize.
		- Solution: let's get rid of rules and try a constraint-only model (OT).
		- Repeated until the semester ends: the constraint-only model can't capture some data, let's revise it to get it to work.
		- At the end of the semester, we won't have a perfect model, but it will capture some generalizations that the original model didn't.
	- The central idea of the course -- upon which everything is structured -- is **phonological argumentation**: how to evaluate, compare, apply, and argue for phonological models. 
	- We'll practice **iterative model development**, building a model to accomplish some goals, testing it with new data, revising, and repeating.
	- Determining the predictions of a model is an essential step in both model argumentation and development, and we'll practice this as much as possible.
- Let's look at [the syllabus](531_syllabus.html).
	- The first few HW assignments will have bonus questions (both easier and harder) to accommodate various backgrounds.
	- Submit work in hard copy, and I'll return it with handwritten comments. 
	- You should save all returned work at least until the end of the semester.
	- Laptops, Dropbox, Slack, and Google docs
		- Dropbox directory contains readings and the Slack invite link
		- We'll use Slack as the course forum for announcements and communication
		- When we collaborate during class, I'll post a google docs link. You won't need an account to collaborate on the sheet
	- Handouts and schedule
		- The schedule is very flexible.
		- Handouts usually span multiple class meetings.
	- To print or not to print?
		- Handouts are viewable on electronic devices, and you can see all of them at the daily schedule, accessible by clicking the link at the top of every page.
		- Trivia: Handouts are typeset using [Markdown syntax](https://guides.github.com/features/mastering-markdown/). 
			- I actually use [MultiMarkdown](https://fletcherpenney.net/multimarkdown/), which is basically Github-flavored Markdown with some nice extensions (especially headerless tables!).
			- The raw code underlying every handout is available at a near-identical URL: replace `.html` with `.txt`.
			- The arcane and hacky CSS is [viewable](bws.css) if you're a masochist and/or web development enthusiast.
- For next time, think of as  many answers as possible to the questions below.
	-   "What are other possible goals of phonological theory?"
	-   "What are phonological data?"

